# Generated by Django 3.0.2 on 2020-01-31 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='events_list',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_description', models.TextField(max_length=255)),
                ('event_venue', models.TextField(max_length=255)),
                ('eventup_date', models.DateTimeField(max_length=30)),
                ('event_post_date', models.DateTimeField(auto_now_add=True)),
                ('event_organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.signup_user')),
            ],
            options={
                'db_table': 'events',
            },
        ),
    ]
