# Generated by Django 3.0 on 2020-01-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='events_list',
            fields=[
                ('event_organizer_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_organizer', models.CharField(max_length=30)),
                ('event_description', models.TextField(max_length=255)),
                ('event_post_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'events',
            },
        ),
    ]
