# Generated by Django 3.0 on 2020-01-18 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20200118_1153'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events_list',
            name='event_organizer',
        ),
        migrations.AddField(
            model_name='events_list',
            name='event_organizerid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='signup.signup_user'),
        ),
    ]
