# Generated by Django 3.0 on 2020-01-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_events_list_eventdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events_list',
            name='eventDate',
            field=models.DateTimeField(max_length=40),
        ),
    ]
