# Generated by Django 3.0 on 2020-01-18 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200118_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events_list',
            name='eventDate',
        ),
    ]
