# Generated by Django 3.0 on 2020-01-18 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_events_list_eventdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events_list',
            old_name='event_organizer_id',
            new_name='event_id',
        ),
    ]
