# Generated by Django 3.0 on 2020-01-21 05:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20200118_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='events_list',
            name='event_date',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
