# Generated by Django 3.0 on 2020-01-21 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20200121_0822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events_list',
            old_name='event_date',
            new_name='eventup_date',
        ),
    ]
