# Generated by Django 3.0 on 2020-01-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20200121_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events_list',
            name='event_post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
