# Generated by Django 3.0 on 2020-01-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiqgallery',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
