# Generated by Django 3.0 on 2020-01-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20200119_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiqgallery',
            name='imagedesscription',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hiqgallery',
            name='image',
            field=models.FileField(max_length=255, upload_to=''),
        ),
    ]
