# Generated by Django 3.0 on 2020-01-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20200122_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiqgallery',
            name='imagedescription',
            field=models.CharField(max_length=255),
        ),
    ]
