# Generated by Django 3.0 on 2020-01-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup_user',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=30)),
                ('Second_name', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=30)),
                ('Phone_Number', models.CharField(max_length=30)),
                ('profilepic', models.ImageField(default='None', upload_to='')),
                ('logstatus', models.BooleanField(default=False, max_length=3)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
