# Generated by Django 3.0.2 on 2020-01-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup_user',
            name='admin_status',
            field=models.BooleanField(default=0, max_length=3),
        ),
    ]
