# Generated by Django 3.0.2 on 2020-01-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20200118_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_user',
            name='Password',
            field=models.CharField(max_length=255),
        ),
    ]
