# Generated by Django 3.0.2 on 2020-01-27 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20200118_1153'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='signup_user',
            table=None,
        ),
    ]
