# Generated by Django 3.0.2 on 2020-01-27 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_auto_20200127_1926'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='signup_user',
            table='users',
        ),
    ]
