# Generated by Django 3.0.2 on 2020-01-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_auto_20200127_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_user',
            name='Password',
            field=models.CharField(max_length=60),
        ),
    ]
