# Generated by Django 3.0.2 on 2020-01-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_auto_20200130_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_user',
            name='Password',
            field=models.CharField(max_length=255),
        ),
    ]
