# Generated by Django 3.0.2 on 2020-01-30 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Feeds', '0001_initial'),
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment_list',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('comments', models.TextField(max_length=255)),
                ('comment_post_time', models.DateTimeField(auto_now_add=True)),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Feeds.feeds_list')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.signup_user')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
