# Generated by Django 3.0 on 2020-01-20 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20200120_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment_list',
            old_name='fid',
            new_name='fid_id',
        ),
    ]
