# Generated by Django 3.0 on 2020-01-20 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20200120_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment_list',
            old_name='fid_id',
            new_name='fid',
        ),
    ]
