# Generated by Django 3.0 on 2020-01-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20200120_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_list',
            name='comments',
            field=models.TextField(max_length=255),
        ),
    ]
