# Generated by Django 3.0 on 2020-01-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_auto_20200122_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_list',
            name='comments',
            field=models.TextField(max_length=1255),
        ),
    ]
