# Generated by Django 3.0 on 2020-01-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_auto_20200122_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_list',
            name='comments',
            field=models.TextField(max_length=255),
        ),
    ]
