# Generated by Django 3.0 on 2020-01-20 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signup', '0002_auto_20200118_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='feeds_list',
            fields=[
                ('Fid', models.AutoField(primary_key=True, serialize=False)),
                ('feed', models.CharField(max_length=255)),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.signup_user')),
            ],
        ),
    ]
