# Generated by Django 3.0 on 2020-01-20 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feeds_list',
            table='feeds',
        ),
    ]
