# Generated by Django 3.0 on 2020-01-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeds_list',
            name='feed_header',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterModelTable(
            name='feeds_list',
            table='feeds',
        ),
    ]
