# Generated by Django 3.0 on 2020-01-21 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feeds', '0002_auto_20200121_1052'),
        ('Feeds', '0002_auto_20200120_1500'),
    ]

    operations = [
    ]
