# Generated by Django 3.0 on 2020-01-21 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feeds', '0004_auto_20200121_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeds_list',
            name='Heading',
        ),
    ]
