# Generated by Django 3.0 on 2020-01-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feeds', '0005_remove_feeds_list_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeds_list',
            name='feed',
            field=models.CharField(max_length=1255),
        ),
    ]
