# Generated by Django 3.0 on 2020-01-18 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectowner', models.EmailField(max_length=50)),
                ('project_name', models.CharField(max_length=30)),
                ('project_description', models.TextField(max_length=255)),
                ('file', models.FileField(upload_to='')),
                ('uploadtime', models.DateTimeField(auto_now_add=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.signup_user')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
    ]
