# Generated by Django 3.0 on 2020-01-18 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_pro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='projectowner',
        ),
    ]
