# Generated by Django 3.0 on 2020-01-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_pro', '0002_remove_project_projectowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='uploadtime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
