# Generated by Django 3.0 on 2020-01-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_pro', '0003_auto_20200118_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
