# Generated by Django 3.0.2 on 2020-01-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_pro', '0004_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Met', 'It')], max_length=30, null=True),
        ),
    ]
