# Generated by Django 3.0.2 on 2020-01-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_pro', '0005_auto_20200129_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Web', 'Website'), ('Android app', 'Android app'), ('Art & poem', 'Art & poem'), ('Not listed', 'Not listed')], max_length=30, null=True),
        ),
    ]
