# Generated by Django 3.0.2 on 2020-01-30 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='suggetionbox',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('suggcontent', models.CharField(default='', max_length=255)),
                ('suggestuser', models.ForeignKey(default=1, max_length=50, on_delete=django.db.models.deletion.CASCADE, to='signup.signup_user')),
            ],
            options={
                'db_table': 'suggetions',
            },
        ),
    ]
