# Generated by Django 3.0.2 on 2020-01-30 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_signup_user_admin_status'),
        ('suggestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='suggetionbox',
            new_name='suggetion_box',
        ),
    ]
