# Generated by Django 3.0.2 on 2020-01-30 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_signup_user_admin_status'),
        ('suggestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='suggetionbox',
            new_name='public_suggetion_box',
        ),
        migrations.RenameField(
            model_name='public_suggetion_box',
            old_name='suggcontent',
            new_name='suggestion',
        ),
        migrations.AlterModelTable(
            name='public_suggetion_box',
            table='psuggetions',
        ),
        migrations.CreateModel(
            name='suggetion_box',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('suggestion', models.CharField(default='', max_length=255)),
                ('suggestuser', models.ForeignKey(default=1, max_length=50, on_delete=django.db.models.deletion.CASCADE, to='signup.signup_user')),
            ],
            options={
                'db_table': 'suggetions',
            },
        ),
    ]
