# Generated by Django 3.0.2 on 2020-01-30 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='suggetion_box',
            table='suggestions',
        ),
    ]
