# Generated by Django 3.0.2 on 2020-01-30 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion', '0002_auto_20200130_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggetion_box',
            old_name='suggestuser',
            new_name='suggestuser_id',
        ),
    ]
