# Generated by Django 3.0.2 on 2020-01-30 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_auto_20200130_1556'),
        ('suggestion', '0002_auto_20200130_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggetionbox',
            name='sugguser',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='signup.signup_user'),
        ),
    ]
