# Generated by Django 3.0.2 on 2020-01-30 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion', '0003_auto_20200130_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggetion_box',
            old_name='suggestuser_id',
            new_name='suggestuser',
        ),
    ]
