# Generated by Django 3.0.2 on 2020-01-30 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_auto_20200130_1556'),
        ('suggestion', '0003_auto_20200130_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggetionbox',
            name='suggcontent',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='suggetionbox',
            name='sugguser',
            field=models.ForeignKey(default=1, max_length=50, on_delete=django.db.models.deletion.CASCADE, to='signup.signup_user'),
        ),
    ]
