# Generated by Django 3.0.2 on 2020-01-30 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion', '0004_auto_20200130_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggetionbox',
            old_name='suid',
            new_name='sid',
        ),
    ]
