# Generated by Django 3.0.2 on 2020-01-30 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion', '0004_auto_20200130_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggetion_box',
            old_name='suggcontent',
            new_name='suggestion',
        ),
    ]
