# Generated by Django 3.0.2 on 2020-01-30 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_signup_user_admin_status'),
        ('suggestion', '0005_auto_20200130_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='public_suggetion_box',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('suggestion', models.CharField(default='', max_length=255)),
                ('suggestuser', models.ForeignKey(default=1, max_length=50, on_delete=django.db.models.deletion.CASCADE, to='signup.signup_user')),
            ],
            options={
                'db_table': 'psuggetions',
            },
        ),
    ]
